### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AlexanderElias** [hunterloftis/cryo#8]
I am trying to stringify objects slightly larger than the example object that I have posted. And I receive the following error.

**Error:**

```
RangeError: Maximum call stack size exceeded
    at Process.hasOwnProperty (native)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:57:20)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
    at cloneWithReferences (/Users/Alex/code/systems/alive/node_modules/cryo/lib/cryo.js:58:26)
```

**Object:**

``` JSON
{"root":"_CRYO_REF_5","references":[{"contents":{},"value":"_CRYO_OBJECT_"},{"contents":{"0":"node","1":"app.js"},"value":"_CRYO_ARRAY_"},{"contents":{"port":9000},"value":"_CRYO_OBJECT_"},{"contents":{"0":"ignore","1":10,"2":11},"value":"_CRYO_ARRAY_"},{"contents":{},"value":"_CRYO_FUNCTION_function (restarts) {\n    return sleep[restarts - 1] || sleep[sleep.length - 1]\n  }"},{"contents":{"domain":null,"_events":"_CRYO_REF_0","_eventsCount":0,"_maxListeners":"_CRYO_UNDEFINED_","id":null,"status":"stopped","command":"_CRYO_REF_1","name":"test","cwd":"/Users/Alex/psudo-server/www/node/_test","env":"_CRYO_REF_2","uid":"_CRYO_UNDEFINED_","gid":"_CRYO_UNDEFINED_","pid":0,"stdio":"_CRYO_REF_3","stdout":"_CRYO_UNDEFINED_","stderr":"_CRYO_UNDEFINED_","windowsVerbatimArguments":"_CRYO_UNDEFINED_","crashed":false,"sleep":"_CRYO_REF_4","maxRestarts":5,"kill":30000,"child":null,"started":null,"timeout":null},"value":"_CRYO_OBJECT_"}]}
```

**Comment by dregre** [comment]
+1

**Comment by booleangate** [comment]
Also getting this error in both `stringify` and `parse` when there is a cycle present.

```js
function Cycle() {}
c1 = new Cycle();
c2 = new Cycle();

c1.c = c2;
c2.c = c1;

r = Cryo.parse(Cryo.stringify({ c1: c1, c2: c2 }))
```
